const GAME_PROTOCOL_NAME = "endlessvoid"

const MSG_TYPE_CLIENT_HANDSHAKE = 1
const MSG_TYPE_CLIENT_KEY_STATE = 2
const MSG_TYPE_SERVER_HANDSHAKE = 3
const MSG_TYPE_SERVER_STATE = 4

export {
    GAME_PROTOCOL_NAME,
    MSG_TYPE_CLIENT_HANDSHAKE,
    MSG_TYPE_CLIENT_KEY_STATE,
    MSG_TYPE_SERVER_HANDSHAKE,
    MSG_TYPE_SERVER_STATE,
}
