const MSG_TYPE_HANDSHAKE_CLIENT = 1
const MSG_TYPE_HANDSHAKE_SERVER = 2
const MSG_TYPE_KEY_STATE = 3
const MSG_TYPE_SERVER_PLAYER_STATE = 4

export {
    MSG_TYPE_HANDSHAKE_CLIENT,
    MSG_TYPE_HANDSHAKE_SERVER,
    MSG_TYPE_KEY_STATE,
    MSG_TYPE_SERVER_PLAYER_STATE,
}
